# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eC1QSheguQ5S7LcbcI3twhtozHqUSbTf
"""

# ✅ إزالة sympy نهائياً
!pip uninstall sympy -y

# ✅ تثبيت إصدار محدد يعمل بدون مشاكل
!pip install sympy==1.12

# ✅ إعادة تثبيت transformers و gradio
!pip install --upgrade transformers gradio -q

from transformers import pipeline
import gradio as gr

# ✅ تحميل النموذج (باستخدام PyTorch لتجنب تعارضات)
generator = pipeline("text-generation", model="aubmindlab/aragpt2-base")

# ✅ دالة التخمين
def guess_entity(desc1, desc2, desc3):
    clues = f"{desc1}, {desc2}, {desc3}"
    prompt = f"أنا لعبة من أنا. تم إعطائي الأوصاف التالية: {clues}. من أكون؟"
    print("🚀 Prompt:", prompt)  # لمساعدتك في التصحيح إذا احتجت
    try:
        result = generator(prompt, max_new_tokens=50, num_return_sequences=1)[0]["generated_text"]
        guess = result[len(prompt):].strip().split('\n')[0]
        return f"🤖 تخميني هو: {guess}"
    except Exception as e:
        return f"❌ حصل خطأ أثناء التخمّين: {str(e)}"

# ✅ تصميم الواجهة
interface = gr.Interface(
    fn=guess_entity,
    inputs=[
        gr.Textbox(label="🧩 الوصف الأول"),
        gr.Textbox(label="🧩 الوصف الثاني"),
        gr.Textbox(label="🧩 الوصف الثالث")
    ],
    outputs=gr.Textbox(label="🔍 تخمين الذكاء الاصطناعي"),
    title="🎭 لعبة من أنا؟",
    description="😊 اكتب 3 أوصاف وسأحاول أن أخمّن من تقصد! جربني"
)

# ✅ تشغيل التطبيق
interface.launch(share=True)